In [1]:
l = [2345, 27, 546, 215, -1234]

In [2]:
l

[2345, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([ 2345,    27,   546,   215, -1234])

In [7]:
b = np.array([12,455,63.3, True, "abc"])

In [8]:
b

array(['12', '455', '63.3', 'True', 'abc'],
      dtype='<U32')

In [9]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [10]:
l.pop()

-1234

In [11]:
l

[2345, 27, 546, 215]

In [12]:
a.mean()

379.80000000000001

In [13]:
c = np.array([1,2,3,True])

In [14]:
c

array([1, 2, 3, 1])

In [16]:
print(c)

[1 2 3 1]


In [17]:
l

[2345, 27, 546, 215]

In [18]:
myList = [ 12345, 23, 100, 44444, 9090, 3, 1000]

In [19]:
myList[:]

[12345, 23, 100, 44444, 9090, 3, 1000]

In [20]:
myList[::3]

[12345, 44444, 1000]

In [21]:
myList[::4]

[12345, 9090]

In [22]:
myList[1:4]

[23, 100, 44444]

In [23]:
myList[3:-1]

[44444, 9090, 3]

In [24]:
myList[:-3]

[12345, 23, 100, 44444]

In [25]:
myList[1:3:-2]

[]

In [26]:
myList[4:2]

[]

In [27]:
myList[-2:-4]

[]

In [28]:
myList[-4:-2]

[44444, 9090]

In [29]:
myList

[12345, 23, 100, 44444, 9090, 3, 1000]

In [30]:
a

array([ 2345,    27,   546,   215, -1234])

In [31]:
a[2:]

array([  546,   215, -1234])

In [32]:
a[2:4]

array([546, 215])

In [33]:
b = a[2:4]

In [34]:
b[0]

546

In [35]:
b[:] = 111

In [36]:
a

array([ 2345,    27,   111,   111, -1234])

In [37]:
c = a.copy()

In [38]:
c

array([ 2345,    27,   111,   111, -1234])

In [39]:
c[4] = 5555

In [40]:
c

array([2345,   27,  111,  111, 5555])

In [41]:
a

array([ 2345,    27,   111,   111, -1234])